!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.15 (master) - 15 Apr 2020 11:54
!
MODULE MODELS_DIFF
  IMPLICIT NONE

CONTAINS
! split data
  SUBROUTINE GETDATAACTIVITY(modelname, npardata, pardata, a, alpha, r)
    IMPLICIT NONE
    CHARACTER(len=20), INTENT(IN) :: modelname
    INTEGER, INTENT(IN) :: npardata
    DOUBLE PRECISION, INTENT(IN) :: pardata(npardata)
    DOUBLE PRECISION, DIMENSION(3, 3), INTENT(OUT) :: a, alpha
    DOUBLE PRECISION, INTENT(OUT) :: r
    INTRINSIC TRIM
    SELECT CASE  (TRIM(modelname))
    CASE ('NRTL', 'nrtl')
!! Matrix A of binary interaction
      a(1, :) = pardata(1:3)
      a(2, :) = pardata(4:6)
      a(3, :) = pardata(7:9)
!! Symetric matrix Alpha
      alpha(1, :) = pardata(10:12)
      alpha(2, :) = pardata(13:15)
      alpha(3, :) = pardata(16:18)
!! The constant R
      r = pardata(19)
    CASE ('UNIQUAC', 'uniquac', 'WILSON', 'wilson')

    CASE DEFAULT
      WRITE(*, *) 'Wrong choice of model.'
      STOP
    END SELECT
  END SUBROUTINE GETDATAACTIVITY

  SUBROUTINE GETDATAPRESSURE(modelname, npardata, pardata, antoinea, &
&   antoineb, antoinec)
    IMPLICIT NONE
    CHARACTER(len=20), INTENT(IN) :: modelname
    INTEGER, INTENT(IN) :: npardata
    DOUBLE PRECISION, INTENT(IN) :: pardata(npardata)
    DOUBLE PRECISION, DIMENSION(3), INTENT(OUT) :: antoinea, antoineb, &
&   antoinec
    INTRINSIC TRIM
    SELECT CASE  (TRIM(modelname))
    CASE ('ANTOINE', 'antoine')
!! Antoine's Equation constants
      antoinea = pardata(1:3)
      antoineb = pardata(4:6)
      antoinec = pardata(7:9)
    CASE ('DIPPR', 'dippr')

    CASE DEFAULT
      WRITE(*, *) 'Wrong choice of model.'
      STOP
    END SELECT
  END SUBROUTINE GETDATAPRESSURE

!  Differentiation of getpressure in forward (tangent) mode:
!   variations   of useful results: pression
!   with respect to varying inputs: temperature
  SUBROUTINE GETPRESSURE_D(temperature, temperatured, modelname, &
&   modelpars_dim, modelpars, pression, pressiond)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: temperature
    DOUBLE PRECISION, INTENT(IN) :: temperatured
    CHARACTER(len=20), INTENT(IN) :: modelname
    INTEGER, INTENT(IN) :: modelpars_dim
    DOUBLE PRECISION, INTENT(IN) :: modelpars(modelpars_dim)
    DOUBLE PRECISION, INTENT(OUT) :: pression(3)
    DOUBLE PRECISION, INTENT(OUT) :: pressiond(3)
! on calcule p en fonction du modèle
! attention, la taille du vecteur de paramètres modelpars dépend de modelname
! modelname = 'antoine', 'dippr'
! Local variables
    DOUBLE PRECISION, DIMENSION(3) :: antoinea, antoineb, antoinec
    INTEGER :: n
    DOUBLE PRECISION :: t
    DOUBLE PRECISION :: td
!! Loop indice
    INTEGER :: i
    INTRINSIC TRIM
    DOUBLE PRECISION :: pwy1
    DOUBLE PRECISION :: pwy1d
    DOUBLE PRECISION :: temp
    td = temperatured
    t = temperature
    n = 3
! get data
    CALL GETDATAPRESSURE(modelname, modelpars_dim, modelpars, antoinea, &
&                  antoineb, antoinec)
    SELECT CASE  (TRIM(modelname))
    CASE ('ANTOINE', 'antoine')
      pressiond = 0.D0
!! Antoine model
!! Calcul des pressions partielles Pi en utilisant l'equation d'antoine
      DO i=1,n,1
        temp = antoineb(i)/(antoinec(i)+t)
        pwy1d = temp*td/(antoinec(i)+t)
        pwy1 = antoinea(i) - temp
        temp = 10d0**pwy1
        pressiond(i) = temp*LOG(10d0)*pwy1d
        pression(i) = temp
      END DO
    CASE ('DIPPR', 'dippr')
      pressiond = 0.D0
    CASE DEFAULT
      WRITE(*, *) 'Wrong choice of model.'
      STOP
    END SELECT
  END SUBROUTINE GETPRESSURE_D

  SUBROUTINE GETPRESSURE(temperature, modelname, modelpars_dim, &
&   modelpars, pression)
    IMPLICIT NONE
    DOUBLE PRECISION, INTENT(IN) :: temperature
    CHARACTER(len=20), INTENT(IN) :: modelname
    INTEGER, INTENT(IN) :: modelpars_dim
    DOUBLE PRECISION, INTENT(IN) :: modelpars(modelpars_dim)
    DOUBLE PRECISION, INTENT(OUT) :: pression(3)
! on calcule p en fonction du modèle
! attention, la taille du vecteur de paramètres modelpars dépend de modelname
! modelname = 'antoine', 'dippr'
! Local variables
    DOUBLE PRECISION, DIMENSION(3) :: antoinea, antoineb, antoinec
    INTEGER :: n
    DOUBLE PRECISION :: t
!! Loop indice
    INTEGER :: i
    INTRINSIC TRIM
    DOUBLE PRECISION :: pwy1
    t = temperature
    n = 3
! get data
    CALL GETDATAPRESSURE(modelname, modelpars_dim, modelpars, antoinea, &
&                  antoineb, antoinec)
    SELECT CASE  (TRIM(modelname))
    CASE ('ANTOINE', 'antoine')
!! Antoine model
!! Calcul des pressions partielles Pi en utilisant l'equation d'antoine
      DO i=1,n,1
        pwy1 = antoinea(i) - antoineb(i)/(t+antoinec(i))
        pression(i) = 10d0**pwy1
      END DO
    CASE ('DIPPR', 'dippr')

    CASE DEFAULT
      WRITE(*, *) 'Wrong choice of model.'
      STOP
    END SELECT
  END SUBROUTINE GETPRESSURE

!  Differentiation of getkaux in forward (tangent) mode:
!   variations   of useful results: kaux
!   with respect to varying inputs: temperature concentrations
  SUBROUTINE GETKAUX_D(concentrations, concentrationsd, temperature, &
&   temperatured, modelname_p, modelpars_p_dim, modelpars_p, modelname_g&
&   , modelpars_g_dim, modelpars_g, p0, kaux, kauxd)
    IMPLICIT NONE
    DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: concentrations
    DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: concentrationsd
    DOUBLE PRECISION, INTENT(IN) :: temperature
    DOUBLE PRECISION, INTENT(IN) :: temperatured
    CHARACTER(len=20), INTENT(IN) :: modelname_p, modelname_g
    INTEGER, INTENT(IN) :: modelpars_p_dim, modelpars_g_dim
    DOUBLE PRECISION, INTENT(IN) :: modelpars_p(modelpars_p_dim), &
&   modelpars_g(modelpars_g_dim)
    INTEGER, INTENT(IN) :: p0
    DOUBLE PRECISION, INTENT(OUT) :: kaux(2)
    DOUBLE PRECISION, INTENT(OUT) :: kauxd(2)
! Local variables
    DOUBLE PRECISION, DIMENSION(3, 3) :: a, alpha
    DOUBLE PRECISION :: r
    INTEGER :: n
!
    DOUBLE PRECISION :: x(3), t
    DOUBLE PRECISION :: xd(3), td
!
!! Loop indice
    INTEGER :: i, j
    DOUBLE PRECISION :: fr1, fr2, fr3, fr4, fr5, fr6
    DOUBLE PRECISION :: fr1d, fr2d
    DOUBLE PRECISION, DIMENSION(3, 3) :: tho, g
    DOUBLE PRECISION, DIMENSION(3, 3) :: thod, gd
    DOUBLE PRECISION, DIMENSION(3) :: pression
    DOUBLE PRECISION, DIMENSION(3) :: pressiond
    INTRINSIC EXP
    DOUBLE PRECISION :: arg1
    DOUBLE PRECISION :: arg1d
    DOUBLE PRECISION :: temp
    DOUBLE PRECISION :: temp0
    DOUBLE PRECISION :: temp1
    DOUBLE PRECISION :: temp2
! get data
    CALL GETPRESSURE_D(temperature, temperatured, modelname_p, &
&                modelpars_p_dim, modelpars_p, pression, pressiond)
    CALL GETDATAACTIVITY(modelname_g, modelpars_g_dim, modelpars_g, a, &
&                  alpha, r)
    xd = concentrationsd
    x = concentrations
    td = temperatured
    t = temperature
!! Initialisation of the local variables at zero
    fr1 = 0d0
    fr2 = 0d0
    n = 3
    thod = 0.D0
!!*****************************************************************************************************************
!!!!!!!!!!!!!!!!!!!!!!!!!!CALCULATION OF ALL PARAMETERS NEEDED TO COSNTRUCT THE EDA SYSTEM!!!!!!!!!!!!!!!!!!!!!!!!!
!!*****************************************************************************************************************
!! Construction of tho(i,j)
    DO i=1,n,1
      DO j=1,n,1
        temp = a(i, j)/(r*(t+273.15))
        thod(i, j) = -(temp*td/(t+273.15))
        tho(i, j) = temp
      END DO
    END DO
    gd = 0.D0
!! Construction of G(i,j)
    DO i=1,n,1
      DO j=1,n,1
        temp = -(alpha(i, j)*tho(i, j))
        gd(i, j) = -(EXP(temp)*alpha(i, j)*thod(i, j))
        g(i, j) = EXP(temp)
      END DO
    END DO
!!*****************************************************************************************************************
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!CONSTRUCTION OF THE EDA SYSTEM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!*****************************************************************************************************************
!! Calculation of the equilibrium constants in the case of a binary mixture (getAzeotropeBinary)
!! The binary case when substance 3 is absent
    fr1d = 2*(x(1)*g(1, 2)-x(1)+1)*((g(1, 2)-1.0)*xd(1)+x(1)*gd(1, 2))
    fr1 = (1-x(1)+x(1)*g(1, 2))**2
    fr2d = 2*(x(1)+(1-x(1))*g(2, 1))*((1.0-g(2, 1))*xd(1)+(1-x(1))*gd(2&
&     , 1))
    fr2 = (x(1)+(1-x(1))*g(2, 1))**2
    temp = tho(1, 2)/fr1
    temp0 = fr2**0.5d0*fr2**0.5d0
    temp1 = tho(2, 1)*(g(2, 1)*g(2, 1))/temp0
    temp2 = temp1 + temp*g(1, 2)
    arg1d = (1-x(1))**2*((g(2, 1)**2*thod(2, 1)+tho(2, 1)*2*g(2, 1)*gd(2&
&     , 1)-temp1*2*fr2**0.5d0*0.5d0*fr2**(-0.5D0)*fr2d)/temp0+g(1, 2)*(&
&     thod(1, 2)-temp*fr1d)/fr1+temp*gd(1, 2)) - temp2*2*(1-x(1))*xd(1)
    arg1 = (1-x(1))*(1-x(1))*temp2
    kauxd = 0.D0
    temp2 = EXP(arg1)
    temp1 = pression(1)/p0
    kauxd(1) = temp2*pressiond(1)/p0 + temp1*EXP(arg1)*arg1d
    kaux(1) = temp1*temp2
    temp2 = tho(2, 1)/fr2
    temp1 = fr1**0.5d0*fr1**0.5d0
    temp0 = tho(1, 2)*(g(1, 2)*g(1, 2))/temp1
    temp = temp0 + temp2*g(2, 1)
    arg1d = temp*2*x(1)*xd(1) + x(1)**2*((g(1, 2)**2*thod(1, 2)+tho(1, 2&
&     )*2*g(1, 2)*gd(1, 2)-temp0*2*fr1**0.5d0*0.5d0*fr1**(-0.5D0)*fr1d)/&
&     temp1+g(2, 1)*(thod(2, 1)-temp2*fr2d)/fr2+temp2*gd(2, 1))
    arg1 = x(1)*x(1)*temp
    temp2 = EXP(arg1)
    temp1 = pression(2)/p0
    kauxd(2) = temp2*pressiond(2)/p0 + temp1*EXP(arg1)*arg1d
    kaux(2) = temp1*temp2
  END SUBROUTINE GETKAUX_D

  SUBROUTINE GETKAUX(concentrations, temperature, modelname_p, &
&   modelpars_p_dim, modelpars_p, modelname_g, modelpars_g_dim, &
&   modelpars_g, p0, kaux)
    IMPLICIT NONE
    DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: concentrations
    DOUBLE PRECISION, INTENT(IN) :: temperature
    CHARACTER(len=20), INTENT(IN) :: modelname_p, modelname_g
    INTEGER, INTENT(IN) :: modelpars_p_dim, modelpars_g_dim
    DOUBLE PRECISION, INTENT(IN) :: modelpars_p(modelpars_p_dim), &
&   modelpars_g(modelpars_g_dim)
    INTEGER, INTENT(IN) :: p0
    DOUBLE PRECISION, INTENT(OUT) :: kaux(2)
! Local variables
    DOUBLE PRECISION, DIMENSION(3, 3) :: a, alpha
    DOUBLE PRECISION :: r
    INTEGER :: n
!
    DOUBLE PRECISION :: x(3), t
!
!! Loop indice
    INTEGER :: i, j
    DOUBLE PRECISION :: fr1, fr2, fr3, fr4, fr5, fr6
    DOUBLE PRECISION, DIMENSION(3, 3) :: tho, g
    DOUBLE PRECISION, DIMENSION(3) :: pression
    INTRINSIC EXP
    DOUBLE PRECISION :: arg1
! get data
    CALL GETPRESSURE(temperature, modelname_p, modelpars_p_dim, &
&              modelpars_p, pression)
    CALL GETDATAACTIVITY(modelname_g, modelpars_g_dim, modelpars_g, a, &
&                  alpha, r)
    x = concentrations
    t = temperature
!! Initialisation of the local variables at zero
    fr1 = 0d0
    fr2 = 0d0
    n = 3
!!*****************************************************************************************************************
!!!!!!!!!!!!!!!!!!!!!!!!!!CALCULATION OF ALL PARAMETERS NEEDED TO COSNTRUCT THE EDA SYSTEM!!!!!!!!!!!!!!!!!!!!!!!!!
!!*****************************************************************************************************************
!! Construction of tho(i,j)
    DO i=1,n,1
      DO j=1,n,1
        tho(i, j) = a(i, j)/(r*(t+273.15))
      END DO
    END DO
!! Construction of G(i,j)
    DO i=1,n,1
      DO j=1,n,1
        g(i, j) = EXP(-(alpha(i, j)*tho(i, j)))
      END DO
    END DO
!!*****************************************************************************************************************
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!CONSTRUCTION OF THE EDA SYSTEM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!*****************************************************************************************************************
!! Calculation of the equilibrium constants in the case of a binary mixture (getAzeotropeBinary)
!! The binary case when substance 3 is absent
    fr1 = (1-x(1)+x(1)*g(1, 2))**2
    fr2 = (x(1)+(1-x(1))*g(2, 1))**2
    arg1 = (1-x(1))**2*(tho(2, 1)*(g(2, 1)/fr2**0.5d0)**2+tho(1, 2)*g(1&
&     , 2)/fr1)
    kaux(1) = pression(1)*EXP(arg1)/p0
    arg1 = x(1)**2*(tho(1, 2)*(g(1, 2)/fr1**0.5d0)**2+tho(2, 1)*g(2, 1)/&
&     fr2)
    kaux(2) = pression(2)*EXP(arg1)/p0
  END SUBROUTINE GETKAUX

END MODULE MODELS_DIFF
!		!! The binary case or substance 1 is absent
!		fr3 = ((1 - x(2)) + x(2)*G(2,3))**2
!		fr4 = (x(2) + (1 - x(2))*G(3,2))**2
!		Kaux(3) = pression(2)*exp((1 - x(2))**2*(tho(3,2)*(G(3,2)/fr4**(0.5d0))**2 + tho(2,3)*G(2,3)/fr3))/P0
!		Kaux(4) = pression(3)*exp(x(2)**2*(tho(2,3)*(G(2,3)/fr3**(0.5d0))**2 + tho(3,2)*G(3,2)/fr4))/P0
!		!! The binary case or substance 2 is absent
!		fr5 = ((1 - x(1)) + x(1)*G(1,3))**2
!		fr6 = (x(1) + (1 - x(1))*G(3,1))**2
!		Kaux(5) = pression(1)*exp((1 - x(1))**2*(tho(3,1)*(G(3,1)/fr6**(0.5d0))**2 + tho(1,3)*G(1,3)/fr5))/P0
!		Kaux(6) = pression(3)*exp(x(1)**2*(tho(1,3)*(G(1,3)/fr5**(0.5d0))**2 + tho(3,1)*G(3,1)/fr6))/P0
