services:

  backend_django:
    build:
      context: ./backend_django/
    command: gunicorn backend_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend_django/:/app/
      - static:/app/static/
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - django_network

  nginx:
    build:
      context: ./nginx/
    volumes:
      - static:/app/static/
    ports:
      - 8080:80
    depends_on:
      - backend_django
    networks:
      - django_network

  ms-smith-python:
    build:
      context: ./ms-smith-python/
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    expose:
      - 5000
    env_file:
      - ./ms-smith-python/.env
    networks:
      - django_network

  # ms-smith-julia:
  #   build:
  #     context: ./ms-smith-julia/
  #   command: julia main.jl # le port est défini dans le fichier main.jl
  #   expose:
  #     - 5000
  #   networks:
  #     - django_network

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./db/.env
    networks:
      - django_network

networks:
  django_network:
    name: django_network


volumes:
  static:
    name: static
  db_data:
    name: db_data
