# Generated by Django 4.1.6 on 2023-02-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BinaryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a12', models.FloatField()),
                ('a21', models.FloatField()),
                ('alpha', models.FloatField()),
                ('component1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component1', to='ternary_azeotrope.component')),
                ('component2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component2', to='ternary_azeotrope.component')),
            ],
        ),
        migrations.AddConstraint(
            model_name='binaryrelation',
            constraint=models.UniqueConstraint(fields=('component1', 'component2'), name='unique_components'),
        ),
    ]
