# Generated by Django 4.1.6 on 2023-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ternary_azeotrope", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryrelation",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="component",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
