# Generated by Django 4.1.6 on 2023-02-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ternary_azeotrope",
            "0002_alter_binaryrelation_id_alter_component_id",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
