# Generated by Django 4.1.6 on 2023-02-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("ternary_azeotrope", "0002_delete_test_component_sessions"),
    ]

    operations = [
        migrations.AddField(
            model_name="binaryrelation",
            name="sessions",
            field=models.ManyToManyField(
                blank=True, related_name="relations", to="sessions.session"
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="sessions",
            field=models.ManyToManyField(
                blank=True, related_name="components", to="sessions.session"
            ),
        ),
    ]
