# Generated by Django 4.1.6 on 2023-02-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ternary_azeotrope", "0004_alter_binaryrelation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
