# Generated by Django 4.1.6 on 2023-02-16 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ternary_azeotrope", "0006_alter_component_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("name", "a", "b", "c")},
        ),
    ]
