# Generated by Django 4.1.6 on 2023-02-16 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ternary_azeotrope", "0007_alter_component_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="component",
            unique_together=set(),
        ),
    ]
