# Generated by Django 4.1.6 on 2023-02-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ternary_azeotrope", "0008_alter_component_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="id",
        ),
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False
            ),
        ),
    ]
