# Generated by Django 4.1.6 on 2023-02-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("ternary_azeotrope", "0009_remove_component_id_alter_component_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="id",
            field=models.AutoField(
                default=1, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="sessions",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="sessions.session"
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
