# Generated by Django 4.1.6 on 2023-02-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ternary_azeotrope",
            "0010_component_id_component_sessions_alter_component_name",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="sessions",
        ),
        migrations.AlterField(
            model_name="component",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
