!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.15 (master) - 15 Apr 2020 11:54
!
!  Differentiation of f3 in forward (tangent) mode:
!   variations   of useful results: y
!   with respect to varying inputs: x
!   RW status of diff variables: x:in y:out
!!------------------------------------------------------------------------------------------------------
!! PROJET ALCOS 2017
!>  \ problemDefinition
!!  \brief Shooting function. (EDA System characterizes the azeotrope ternary)
!!  \param[in] ny       Shooting variable dimension (in our case ny=3)
!!  \param[in] y        Shooting variable (in our case y = [x1 x2 T])
!!  \param[in] npar     Number of optional parameters
!!  \param[in] par      Optional parameters
!!
!!  \param[out] s       Shooting value, same dimension as y (EDA system)

MODULE mod_F3d
	IMPLICIT NONE

	CONTAINS

	SUBROUTINE F3_D(x, xd, modelname_p, modelpars_p_dim, modelpars_p, &
	& modelname_g, modelpars_g_dim, modelpars_g, y, yd)
	  USE MODELS_DIFF
	  IMPLICIT NONE
	  INTEGER, INTENT(IN) :: modelpars_p_dim, modelpars_g_dim
	  CHARACTER(len=20), INTENT(IN) :: modelname_p, modelname_g
	  DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: x
	  DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: xd
	  DOUBLE PRECISION, DIMENSION(modelpars_p_dim), INTENT(IN) :: &
	& modelpars_p
	  DOUBLE PRECISION, DIMENSION(modelpars_g_dim), INTENT(IN) :: &
	& modelpars_g
	  DOUBLE PRECISION, DIMENSION(3), INTENT(OUT) :: y
	  DOUBLE PRECISION, DIMENSION(3), INTENT(OUT) :: yd
	! local variables
	  DOUBLE PRECISION :: concentrations(3), temperature, k(3)
	  DOUBLE PRECISION :: concentrationsd(3), temperatured, kd(3)
          double precision,  dimension(3)     :: dipprA, dipprB, dipprC, dipprD, dipprE
	  INTEGER :: p0
	  INTRINSIC TRIM
	  SELECT CASE  (TRIM(modelname_p))
	  CASE ('Antoine', 'antoine')
	    p0 = 760
	  CASE ('DIPPR', 'dippr')
	    call GETDATAPRESSURE_DIPPR(modelname_p, modelpars_p_dim, modelpars_p, dipprA, dipprB, dipprC, dipprD, dipprE, P0)
	  CASE DEFAULT
	    WRITE(*, *) 'Wrong choice of model.'
	    STOP
	  END SELECT
	! x = (x1, x2, T)
	  concentrationsd = 0.D0
	  concentrationsd(1) = xd(1)
	  concentrations(1) = x(1)
	  concentrationsd(2) = xd(2)
	  concentrations(2) = x(2)
	  concentrationsd(3) = -xd(2) - xd(1)
	  concentrations(3) = 1d0 - x(1) - x(2)
	  temperatured = xd(3)
	  temperature = x(3)
	  CALL GETK_D(concentrations, concentrationsd, temperature, temperatured&
	&       , modelname_p, modelpars_p_dim, modelpars_p, modelname_g, &
	&       modelpars_g_dim, modelpars_g, p0, k, kd)
	  yd = 0.D0
	  yd(1) = (1d0-k(1))*concentrationsd(1) - concentrations(1)*kd(1)
	  y(1) = (1d0-k(1))*concentrations(1)
	  yd(2) = (1d0-k(2))*concentrationsd(2) - concentrations(2)*kd(2)
	  y(2) = (1d0-k(2))*concentrations(2)
	  yd(3) = (1d0-k(3))*concentrationsd(3) - concentrations(3)*kd(3)
	  y(3) = (1d0-k(3))*concentrations(3)
	END SUBROUTINE F3_D

	!!------------------------------------------------------------------------------------------------------
	!! PROJET ALCOS 2017
	!>  \ problemDefinition
	!!  \brief Shooting function. (EDA System characterizes the azeotrope ternary)
	!!  \param[in] ny       Shooting variable dimension (in our case ny=3)
	!!  \param[in] y        Shooting variable (in our case y = [x1 x2 T])
	!!  \param[in] npar     Number of optional parameters
	!!  \param[in] par      Optional parameters
	!!
	!!  \param[out] s       Shooting value, same dimension as y (EDA system)
	SUBROUTINE F3_C(x, modelname_p, modelpars_p_dim, modelpars_p, &
	& modelname_g, modelpars_g_dim, modelpars_g, y)
	  USE MODELS_DIFF
	  IMPLICIT NONE
	  INTEGER, INTENT(IN) :: modelpars_p_dim, modelpars_g_dim
	  CHARACTER(len=20), INTENT(IN) :: modelname_p, modelname_g
	  DOUBLE PRECISION, DIMENSION(3), INTENT(IN) :: x
	  DOUBLE PRECISION, DIMENSION(modelpars_p_dim), INTENT(IN) :: &
	& modelpars_p
	  DOUBLE PRECISION, DIMENSION(modelpars_g_dim), INTENT(IN) :: &
	& modelpars_g
	  DOUBLE PRECISION, DIMENSION(3), INTENT(OUT) :: y
	! local variables
	  DOUBLE PRECISION :: concentrations(3), temperature, k(3)
	  double precision,  dimension(3)     :: dipprA, dipprB, dipprC, dipprD, dipprE
	  INTEGER :: p0
	  INTRINSIC TRIM
	  SELECT CASE  (TRIM(modelname_p))
	  CASE ('Antoine', 'antoine')
	    p0 = 760
	  CASE ('DIPPR', 'dippr')
	    call GETDATAPRESSURE_DIPPR(modelname_p, modelpars_p_dim, modelpars_p, dipprA, dipprB, dipprC, dipprD, dipprE, P0)
	  CASE DEFAULT
	    WRITE(*, *) 'Wrong choice of model.'
	    STOP
	  END SELECT
	! x = (x1, x2, T)
	  concentrations(1) = x(1)
	  concentrations(2) = x(2)
	  concentrations(3) = 1d0 - x(1) - x(2)
	  temperature = x(3)
	  CALL GETK(concentrations, temperature, modelname_p, modelpars_p_dim, &
	&     modelpars_p, modelname_g, modelpars_g_dim, modelpars_g, p0, k)
	  y(1) = (1d0-k(1))*concentrations(1)
	  y(2) = (1d0-k(2))*concentrations(2)
	  y(3) = (1d0-k(3))*concentrations(3)
	END SUBROUTINE F3_C

END MODULE mod_F3d
