!        Generated by TAPENADE     (INRIA, Ecuador team)
!  Tapenade 3.15 (master) - 15 Apr 2020 11:54
!
!  Differentiation of fcurve in forward (tangent) mode:
!   variations   of useful results: y
!   with respect to varying inputs: x beta
!   RW status of diff variables: x:in y:out beta:in
MODULE MOD_CURVE

	CONTAINS
	SUBROUTINE FCURVE_D(x, xd, beta, betad, modelname_p, npars_p, pars_p, &
	& modelname_g, npars_g, pars_g, indi, indj, y, yd)
	  USE MODELS_DIFF
	  IMPLICIT NONE
	  INTEGER, INTENT(IN) :: npars_p, npars_g, indi, indj
	  CHARACTER(len=20), INTENT(IN) :: modelname_p, modelname_g
	  DOUBLE PRECISION, DIMENSION(2), INTENT(IN) :: x
	  DOUBLE PRECISION, DIMENSION(2), INTENT(IN) :: xd
	  DOUBLE PRECISION, INTENT(IN) :: beta
	  DOUBLE PRECISION, INTENT(IN) :: betad
	  DOUBLE PRECISION, DIMENSION(npars_p), INTENT(IN) :: pars_p
	  DOUBLE PRECISION, DIMENSION(npars_g), INTENT(IN) :: pars_g
	  DOUBLE PRECISION, DIMENSION(2), INTENT(OUT) :: y
	  DOUBLE PRECISION, DIMENSION(2), INTENT(OUT) :: yd
	!!------------------------------------------------------------------------------------------------------
	!! DEFINITION OF THE LOCAL VARIABLES AND INITIALISATION
	!!------------------------------------------------------------------------------------------------------
	! x(1) = alpha = x2
	! x(2) = temperature
	! beta = x1
	!! Local variables
	  DOUBLE PRECISION :: concentrations(3), temperature, k(3)
	  DOUBLE PRECISION :: concentrationsd(3), temperatured, kd(3)
	  INTEGER :: p0
	  INTRINSIC TRIM
	  SELECT CASE  (TRIM(modelname_p))
	  CASE ('Antoine', 'antoine')
		p0 = 760
	  CASE ('DIPPR', 'dippr')
		p0 = 101325
	  CASE DEFAULT
		WRITE(*, *) 'Wrong choice of model.'
		STOP
	  END SELECT
	  temperatured = xd(2)
	  temperature = x(2)
	  concentrationsd = 0.D0
	  concentrationsd(1) = betad
	  concentrations(1) = beta
	  concentrationsd(2) = xd(1)
	  concentrations(2) = x(1)
	  concentrationsd(3) = -concentrationsd(2) - concentrationsd(1)
	  concentrations(3) = 1d0 - concentrations(1) - concentrations(2)
	  CALL GETK_D(concentrations, concentrationsd, temperature, temperatured&
	&       , modelname_p, npars_p, pars_p, modelname_g, npars_g, pars_g, p0&
	&       , k, kd)
	  yd = 0.D0
	  yd(1) = concentrations(1)*kd(1) + k(1)*concentrationsd(1) + &
	&   concentrations(2)*kd(2) + k(2)*concentrationsd(2) + concentrations(3&
	&   )*kd(3) + k(3)*concentrationsd(3)
	  y(1) = k(1)*concentrations(1) + k(2)*concentrations(2) + k(3)*&
	&   concentrations(3) - 1d0
	  yd(2) = kd(indi) - kd(indj)
	  y(2) = k(indi) - k(indj)
	END SUBROUTINE FCURVE_D

	SUBROUTINE FCURVE_C(x, beta, modelname_p, npars_p, pars_p, modelname_g, &
	& npars_g, pars_g, indi, indj, y)
	  USE MODELS_DIFF
	  IMPLICIT NONE
	  INTEGER, INTENT(IN) :: npars_p, npars_g, indi, indj
	  CHARACTER(len=20), INTENT(IN) :: modelname_p, modelname_g
	  DOUBLE PRECISION, DIMENSION(2), INTENT(IN) :: x
	  DOUBLE PRECISION, INTENT(IN) :: beta
	  DOUBLE PRECISION, DIMENSION(npars_p), INTENT(IN) :: pars_p
	  DOUBLE PRECISION, DIMENSION(npars_g), INTENT(IN) :: pars_g
	  DOUBLE PRECISION, DIMENSION(2), INTENT(OUT) :: y
	!!------------------------------------------------------------------------------------------------------
	!! DEFINITION OF THE LOCAL VARIABLES AND INITIALISATION
	!!------------------------------------------------------------------------------------------------------
	! x(1) = alpha = x2
	! x(2) = temperature
	! beta = x1
	!! Local variables
	  DOUBLE PRECISION :: concentrations(3), temperature, k(3)
	  INTEGER :: p0
	  INTRINSIC TRIM
	  SELECT CASE  (TRIM(modelname_p))
	  CASE ('Antoine', 'antoine')
		p0 = 760
	  CASE ('DIPPR', 'dippr')
		p0 = 101325
	  CASE DEFAULT
		WRITE(*, *) 'Wrong choice of model.'
		STOP
	  END SELECT
	  temperature = x(2)
	  concentrations(1) = beta
	  concentrations(2) = x(1)
	  concentrations(3) = 1d0 - concentrations(1) - concentrations(2)
	  CALL GETK(concentrations, temperature, modelname_p, npars_p, pars_p, &
	&     modelname_g, npars_g, pars_g, p0, k)
	  y(1) = k(1)*concentrations(1) + k(2)*concentrations(2) + k(3)*&
	&   concentrations(3) - 1d0
	  y(2) = k(indi) - k(indj)
	END SUBROUTINE FCURVE_C

END MODULE MOD_CURVE
